# Generated by Django 2.2.6 on 2019-11-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
